/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siswa;

import Index.Index;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class tambah_siswa extends javax.swing.JFrame {
    Connection conn;
    String JK;
   
    public tambah_siswa() {
        initComponents();
        tampilData(); 
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Siswa");
        model.addColumn("Nama Siswa");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Alamat");

        try {
            Connection conn = koneksi.getConnection();
            Statement st = (Statement) conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM siswa");
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_siswa"),
                    rs.getString("nama_siswa"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("tanggal_lahir"),
                    rs.getString("alamat_siswa")
                });
            }
            jTable2.setModel(model);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tambah Data Siswa");

        jLabel2.setText("Nama Siswa:");

        jLabel3.setText("Jenis Kelamin:");

        jLabel4.setText("Tanggal Lahir:");

        jLabel5.setText("Alamat Siswa: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("EDIT");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("HAPUS");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("CLEAR");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Back");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton5))))
                .addGap(0, 458, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection conn = koneksi.getConnection();

            String sql = "INSERT INTO siswa "
                    + "(nama_siswa, jenis_kelamin, tanggal_lahir, alamat_siswa) "
                    + "VALUES (?, ?, ?, ?)";

            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);

            // nama siswa
            pst.setString(1, jTextField1.getText());

            // jenis kelamin dari combobox
            pst.setString(2, jComboBox1.getSelectedItem().toString());

            // tanggal lahir dari JDateChooser
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(jDateChooser1.getDate());

            pst.setString(3, tanggal);

            // alamat siswa
            pst.setString(4, jTextArea1.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

            // reset form
            jTextField1.setText("");
            jComboBox1.setSelectedIndex(0);
            jDateChooser1.setDate(null);
            jTextArea1.setText("");
            jTextField1.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan : " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       new Index().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        int baris = jTable2.getSelectedRow();
         if (baris == -1) {
             JOptionPane.showMessageDialog(this, "Silakan pilih data pada tabel terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
             return;
         }

         if (jTextField1.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(this, "Nama siswa tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
             return;
         }

         String idSiswa = jTable2.getValueAt(baris, 0).toString();

         try {
             Connection conn = koneksi.getConnection();

             String sql = "UPDATE siswa SET nama_siswa=?, jenis_kelamin=?, tanggal_lahir=?, alamat_siswa=? WHERE id_siswa=?";
             PreparedStatement pst = conn.prepareStatement(sql);

             pst.setString(1, jTextField1.getText());
             pst.setString(2, jComboBox1.getSelectedItem().toString());

             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
             String tanggal = sdf.format(jDateChooser1.getDate());
             pst.setString(3, tanggal);

             pst.setString(4, jTextArea1.getText());
             pst.setString(5, idSiswa); 

             // 5. Eksekusi query dan cek hasilnya
             int barisTerdampak = pst.executeUpdate();

             if (barisTerdampak > 0) {
                 JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                 tampilData();                
                 jButton4ActionPerformed(evt); 
             } else {
                 JOptionPane.showMessageDialog(this, "Gagal memperbarui data. ID tidak ditemukan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
             }

         } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
        JK = "Laki-laki";
        } else {
        JK = "Perempuan";
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int baris = jTable2.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data pada tabel yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSiswa = jTable2.getValueAt(baris, 0).toString();
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data siswa ini?", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = koneksi.getConnection();
                String sql = "DELETE FROM siswa WHERE id_siswa=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, idSiswa);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                tampilData();               
                jButton4ActionPerformed(evt); 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    int baris = jTable2.getSelectedRow();
    // Pastikan baris sudah dipilih
    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih data pada tabel terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi nama siswa
    if (jTextField1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama siswa tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi tanggal agar tidak terjadi NullPointerException
    if (jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Tanggal lahir tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // PERBAIKAN: Gunakan jTable2 secara konsisten
    String idSiswa = jTable2.getValueAt(baris, 0).toString();

    try {
        Connection conn = koneksi.getConnection();
        String sql = "UPDATE siswa SET nama_siswa=?, jenis_kelamin=?, tanggal_lahir=?, alamat_siswa=? WHERE id_siswa=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, jTextField1.getText());
        pst.setString(2, jComboBox1.getSelectedItem().toString());

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(jDateChooser1.getDate());
        pst.setString(3, tanggal);

        pst.setString(4, jTextArea1.getText());
        pst.setString(5, idSiswa); 

        // Eksekusi query
        int barisTerdampak = pst.executeUpdate();

        if (barisTerdampak > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampilData();                
            jButton4ActionPerformed(evt); 
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data. ID tidak ditemukan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

        // Praktik yang baik: Tutup koneksi agar tidak memory leak
        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Tambahkan ini untuk melihat detail error di console (Netbeans/Eclipse)
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");        
        jComboBox1.setSelectedIndex(-1);         
        jDateChooser1.setDate(null);        
        jTextArea1.setText("");
        jTextField1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();

        if (baris != -1) {
         
            if (jTable1.getValueAt(baris, 1) != null) {
                jTextField1.setText(jTable1.getValueAt(baris, 1).toString());
            }

            if (jTable1.getValueAt(baris, 2) != null) {
                String jk = jTable1.getValueAt(baris, 2).toString();
                jComboBox1.setSelectedItem(jk);
            }

            if (jTable1.getValueAt(baris, 3) != null) {
                try {
                    String tanggalStr = jTable1.getValueAt(baris, 3).toString();
                    java.util.Date tanggal = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggalStr);
                    jDateChooser1.setDate(tanggal);
                } catch (Exception e) {
                    jDateChooser1.setDate(null);
                }
            }

            if (jTable1.getValueAt(baris, 4) != null) {
                jTextArea1.setText(jTable1.getValueAt(baris, 4).toString());
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tambah_siswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
